# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-10 20:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0023_auto_20220730_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='info1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contest',
            name='info2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contest',
            name='info3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('[\\s]', inverse_match=True)]),
        ),
    ]
