# version: '2.1'

services:
  app:
    platform: linux/x86_64
    restart: always
    build: ./app/
    ports:
    - 9001:8000 # Debugging
    volumes:
    - ./app/:/usr/src/app/ # Debugging
    - static_data:/usr/src/app/static/
    - media_data:/usr/src/app/media/
    depends_on:
    - postgres
    - redis
    env_file:
      - app.env
    environment:
      SESSION_COOKIE_SECURE: 0
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_DB: 1
      GUNICORN_WORKERS: 2
      LOG_HANDLERS: 'file,stderr'


  nginx:
    restart: always
    build: ./nginx/
    ports:
    - 9000:80
    depends_on:
    - app
    volumes:
    - static_data:/usr/src/app/static/:ro
    - media_data:/usr/src/app/media/:ro

  postgres:
    restart: always
    image: postgres:16-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data/
    env_file:
      - postgres.env

  redis:
    restart: always
    image: redis:7.4-alpine

volumes:
  pgdata:
  static_data:
  media_data:
